/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProductRouteImport } from './routes/product'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EngineeringRouteImport } from './routes/engineering'
import { Route as DesignRouteImport } from './routes/design'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CultureRouteImport } from './routes/culture'
import { Route as ArticleEditorRouteImport } from './routes/article-editor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArticleEditorIndexRouteImport } from './routes/article-editor.index'
import { Route as ArticleEditorSlugRouteImport } from './routes/article-editor.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EngineeringRoute = EngineeringRouteImport.update({
  id: '/engineering',
  path: '/engineering',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CultureRoute = CultureRouteImport.update({
  id: '/culture',
  path: '/culture',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleEditorRoute = ArticleEditorRouteImport.update({
  id: '/article-editor',
  path: '/article-editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticleEditorIndexRoute = ArticleEditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticleEditorRoute,
} as any)
const ArticleEditorSlugRoute = ArticleEditorSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticleEditorRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/article-editor': typeof ArticleEditorRouteWithChildren
  '/culture': typeof CultureRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/engineering': typeof EngineeringRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/product': typeof ProductRoute
  '/signup': typeof SignupRoute
  '/article-editor/$slug': typeof ArticleEditorSlugRoute
  '/article-editor/': typeof ArticleEditorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/culture': typeof CultureRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/engineering': typeof EngineeringRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/product': typeof ProductRoute
  '/signup': typeof SignupRoute
  '/article-editor/$slug': typeof ArticleEditorSlugRoute
  '/article-editor': typeof ArticleEditorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/article-editor': typeof ArticleEditorRouteWithChildren
  '/culture': typeof CultureRoute
  '/dashboard': typeof DashboardRoute
  '/design': typeof DesignRoute
  '/engineering': typeof EngineeringRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/product': typeof ProductRoute
  '/signup': typeof SignupRoute
  '/article-editor/$slug': typeof ArticleEditorSlugRoute
  '/article-editor/': typeof ArticleEditorIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/article-editor'
    | '/culture'
    | '/dashboard'
    | '/design'
    | '/engineering'
    | '/login'
    | '/marketing'
    | '/product'
    | '/signup'
    | '/article-editor/$slug'
    | '/article-editor/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/culture'
    | '/dashboard'
    | '/design'
    | '/engineering'
    | '/login'
    | '/marketing'
    | '/product'
    | '/signup'
    | '/article-editor/$slug'
    | '/article-editor'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/article-editor'
    | '/culture'
    | '/dashboard'
    | '/design'
    | '/engineering'
    | '/login'
    | '/marketing'
    | '/product'
    | '/signup'
    | '/article-editor/$slug'
    | '/article-editor/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArticleEditorRoute: typeof ArticleEditorRouteWithChildren
  CultureRoute: typeof CultureRoute
  DashboardRoute: typeof DashboardRoute
  DesignRoute: typeof DesignRoute
  EngineeringRoute: typeof EngineeringRoute
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  ProductRoute: typeof ProductRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engineering': {
      id: '/engineering'
      path: '/engineering'
      fullPath: '/engineering'
      preLoaderRoute: typeof EngineeringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/culture': {
      id: '/culture'
      path: '/culture'
      fullPath: '/culture'
      preLoaderRoute: typeof CultureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article-editor': {
      id: '/article-editor'
      path: '/article-editor'
      fullPath: '/article-editor'
      preLoaderRoute: typeof ArticleEditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/article-editor/': {
      id: '/article-editor/'
      path: '/'
      fullPath: '/article-editor/'
      preLoaderRoute: typeof ArticleEditorIndexRouteImport
      parentRoute: typeof ArticleEditorRoute
    }
    '/article-editor/$slug': {
      id: '/article-editor/$slug'
      path: '/$slug'
      fullPath: '/article-editor/$slug'
      preLoaderRoute: typeof ArticleEditorSlugRouteImport
      parentRoute: typeof ArticleEditorRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ArticleEditorRouteChildren {
  ArticleEditorSlugRoute: typeof ArticleEditorSlugRoute
  ArticleEditorIndexRoute: typeof ArticleEditorIndexRoute
}

const ArticleEditorRouteChildren: ArticleEditorRouteChildren = {
  ArticleEditorSlugRoute: ArticleEditorSlugRoute,
  ArticleEditorIndexRoute: ArticleEditorIndexRoute,
}

const ArticleEditorRouteWithChildren = ArticleEditorRoute._addFileChildren(
  ArticleEditorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArticleEditorRoute: ArticleEditorRouteWithChildren,
  CultureRoute: CultureRoute,
  DashboardRoute: DashboardRoute,
  DesignRoute: DesignRoute,
  EngineeringRoute: EngineeringRoute,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  ProductRoute: ProductRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
